---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: blob-nfs
provisioner: blob.csi.azure.com
parameters:
  protocol: nfs
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nconnect=8  # only supported on linux kernel version >= 5.3
