apiVersion: v1
entries:
  blob-csi-driver:
  - apiVersion: v1
    appVersion: v1.8.0
    created: "2022-01-14T14:55:48.688113766Z"
    description: Azure Blob Storage CSI driver
    digest: ab8800507357a2e35d4d7255b45647cc650134ce3281541bae2130c5833f1f25
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/latest/blob-csi-driver-v1.8.0.tgz
    version: v1.8.0
  - apiVersion: v1
    appVersion: v1.8.0
    created: "2022-01-14T14:55:48.713804716Z"
    description: Azure Blob Storage CSI driver
    digest: 3b78e2ab4f33577c54d4f57276c824717d2ad2aa3741210e938fcaf927bc751f
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.8.0/blob-csi-driver-v1.8.0.tgz
    version: v1.8.0
  - apiVersion: v1
    appVersion: v1.7.0
    created: "2022-01-14T14:55:48.712670409Z"
    description: Azure Blob Storage CSI driver
    digest: 28da5b55c3d2689d6da85eb7da344385e9cb99bdb2af18c24fea93670abfe7ea
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.7.0/blob-csi-driver-v1.7.0.tgz
    version: v1.7.0
  - apiVersion: v1
    appVersion: v1.6.0
    created: "2022-01-14T14:55:48.710992099Z"
    description: Azure Blob Storage CSI driver
    digest: 6f24f2e6623f6f8862e47d4fbdf13b5f351ceec6bb9a4591ef7fc2fca9fc1eef
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.6.0/blob-csi-driver-v1.6.0.tgz
    version: v1.6.0
  - apiVersion: v1
    appVersion: v1.5.0
    created: "2022-01-14T14:55:48.70935329Z"
    description: Azure Blob Storage CSI driver
    digest: 95d14c9b70b319760d388ea47727c8c97e9287867a8852aeb67b7175b52fe8f5
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.5.0/blob-csi-driver-v1.5.0.tgz
    version: v1.5.0
  - apiVersion: v1
    appVersion: v1.4.1
    created: "2022-01-14T14:55:48.707564479Z"
    description: Azure Blob Storage CSI driver
    digest: 5fcf69c449f065fa1d5722e5a7fed8a28000efa790907e9ff4b552c5fbd16d22
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.4.1/blob-csi-driver-v1.4.1.tgz
    version: v1.4.1
  - apiVersion: v1
    appVersion: v1.4.0
    created: "2022-01-14T14:55:48.705683369Z"
    description: Azure Blob Storage CSI driver
    digest: b466543344a6411f6130ba87b093955d39ab8614c6b4ed8505a0a0c96073cb33
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.4.0/blob-csi-driver-v1.4.0.tgz
    version: v1.4.0
  - apiVersion: v1
    appVersion: v1.3.0
    created: "2022-01-14T14:55:48.703011653Z"
    description: Azure Blob Storage CSI driver
    digest: 58d02cb70a3a966b349d62e880b7149fb06ac009474e35e580784fd3c98a5b07
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.3.0/blob-csi-driver-v1.3.0.tgz
    version: v1.3.0
  - apiVersion: v1
    appVersion: v1.2.0
    created: "2022-01-14T14:55:48.701605245Z"
    description: Azure Blob Storage CSI driver
    digest: 27fb89f20b5fddc7329e6d7c2374857b22c1d61592e397a53f47121eea68c344
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.2.0/blob-csi-driver-v1.2.0.tgz
    version: v1.2.0
  - apiVersion: v1
    appVersion: v1.1.0
    created: "2022-01-14T14:55:48.700221737Z"
    description: Azure Blob Storage CSI driver
    digest: a251a55243de207c69ef53f72abee45e93b72fa4fc43dc204b7f1cdfd459acdb
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.1.0/blob-csi-driver-v1.1.0.tgz
    version: v1.1.0
  - apiVersion: v1
    appVersion: v1.0.0
    created: "2022-01-14T14:55:48.698714628Z"
    description: Azure Blob Storage CSI driver
    digest: e83f037a165eafc83a978bd7e6bf6221b052ac34363aecb12e6a73607dc58b89
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.0.0/blob-csi-driver-v1.0.0.tgz
    version: v1.0.0
  - apiVersion: v1
    appVersion: v0.11.0
    created: "2022-01-14T14:55:48.690770682Z"
    description: Azure Blob Storage CSI driver
    digest: ded903d30eaef4f41e2cc7172292089fbaf122cc24cc32f5e62207cff445a9da
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v0.11.0/blob-csi-driver-v0.11.0.tgz
    version: v0.11.0
  - apiVersion: v1
    appVersion: v0.10.0
    created: "2022-01-14T14:55:48.689706176Z"
    description: Azure Blob Storage CSI driver
    digest: 24f3642ce8535544ad63334f9a71eb8c594cc2943becd21844b6b1132d261960
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v0.10.0/blob-csi-driver-v0.10.0.tgz
    version: v0.10.0
  - apiVersion: v1
    appVersion: v0.9.0
    created: "2022-01-14T14:55:48.697512021Z"
    description: Azure Blob Storage CSI driver
    digest: d125014409cad519f12838390c176f81f34097a5ba759a177980255a9fe775e2
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v0.9.0/blob-csi-driver-v0.9.0.tgz
    version: v0.9.0
  - apiVersion: v1
    appVersion: v0.8.0
    created: "2022-01-14T14:55:48.696386414Z"
    description: Azure Blob Storage CSI driver
    digest: 8ac9fc62030ff7c7dd6deaa51db410d9b782578149347688b8f66b37ec33960f
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v0.8.0/blob-csi-driver-v0.8.0.tgz
    version: v0.8.0
  - apiVersion: v1
    appVersion: v0.7.0
    created: "2022-01-14T14:55:48.695322608Z"
    description: Azure Blob Storage CSI driver
    digest: 6d758b8e4a480a8d006f7e73c51d32ea0b568b8ba1364d4ac33549e3bedfc9a7
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v0.7.0/blob-csi-driver-v0.7.0.tgz
    version: v0.7.0
  blobfuse-csi-driver:
  - apiVersion: v1
    appVersion: v0.6.0
    created: "2022-01-14T14:55:48.694225902Z"
    description: BlobFuse Container Storage Interface (CSI) Storage Plugin
    digest: 2bea484bc1e87097b048ab2e1615683b8b7db614059fb624a0a2b18ad0920926
    name: blobfuse-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v0.6.0/blobfuse-csi-driver-v0.6.0.tgz
    version: v0.6.0
  - apiVersion: v1
    appVersion: v0.5.0
    created: "2022-01-14T14:55:48.692886194Z"
    description: BlobFuse Container Storage Interface (CSI) Storage Plugin
    digest: 11441a6025c319e97c0605f520c4be063eadc482670655bb6ecc4426bee2d49c
    name: blobfuse-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v0.5.0/blobfuse-csi-driver-v0.5.0.tgz
    version: v0.5.0
  - apiVersion: v1
    appVersion: v0.4.0
    created: "2022-01-14T14:55:48.691843588Z"
    description: BlobFuse Container Storage Interface (CSI) Storage Plugin
    digest: 263e474a08598f1c7f518c1efed43eb23d9f12b146b3c47deda77aa99c0ca385
    name: blobfuse-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v0.4.0/blobfuse-csi-driver-v0.4.0.tgz
    version: v0.4.0
generated: "2022-01-14T14:55:48.685678452Z"
