apiVersion: v1
entries:
  blob-csi-driver:
  - apiVersion: v1
    appVersion: v1.21.2
    created: "2023-05-12T05:37:18.803451494Z"
    description: Azure Blob Storage CSI driver
    digest: c7adcfeec6e8f6a62cc6d36d10b223d9cad3cfffd2a316380a15fcd615157bbe
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/latest/blob-csi-driver-v1.21.2.tgz
    version: v1.21.2
  - apiVersion: v1
    appVersion: v1.21.2
    created: "2023-05-12T05:37:18.818171159Z"
    description: Azure Blob Storage CSI driver
    digest: a37e16c22dcee86f2e4e56fc6514aedd9061fe9548e82da476c536428b5ccbd8
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.21.2/blob-csi-driver-v1.21.2.tgz
    version: v1.21.2
  - apiVersion: v1
    appVersion: v1.21.1
    created: "2023-05-12T05:37:18.817556577Z"
    description: Azure Blob Storage CSI driver
    digest: 77640358a3862bf482c10fe4d887cbfa84e47d29271a93aecf749c12645ea80e
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.21.1/blob-csi-driver-v1.21.1.tgz
    version: v1.21.1
  - apiVersion: v1
    appVersion: v1.21.0
    created: "2023-05-12T05:37:18.816756278Z"
    description: Azure Blob Storage CSI driver
    digest: cd9d4acb33dca9b76d3780154fbb90de552d1dd09f98641af965c48b26dba0e2
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.21.0/blob-csi-driver-v1.21.0.tgz
    version: v1.21.0
  - apiVersion: v1
    appVersion: v1.20.2
    created: "2023-05-12T05:37:18.816172333Z"
    description: Azure Blob Storage CSI driver
    digest: 4bade95d429e53f9e9e2f07af3e24117f71dbdc708df1f41b6ec95245d2d0ca0
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.20.2/blob-csi-driver-v1.20.2.tgz
    version: v1.20.2
  - apiVersion: v1
    appVersion: v1.20.1
    created: "2023-05-12T05:37:18.815601459Z"
    description: Azure Blob Storage CSI driver
    digest: b2a843345518a2431f7ddd573ec4556cd38a0d4ec78a58703fde4698e545bec3
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.20.1/blob-csi-driver-v1.20.1.tgz
    version: v1.20.1
  - apiVersion: v1
    appVersion: v1.19.3
    created: "2023-05-12T05:37:18.814356018Z"
    description: Azure Blob Storage CSI driver
    digest: 6ce3724c58ae67d89c073ef4940a909cfd1189b47003626a0469ee93878362da
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.19.3/blob-csi-driver-v1.19.3.tgz
    version: v1.19.3
  - apiVersion: v1
    appVersion: v1.19.2
    created: "2023-05-12T05:37:18.813709289Z"
    description: Azure Blob Storage CSI driver
    digest: 63bccd0776f78b6816875ffd99e0ad9c6efecd1b447570228e58410e36dab477
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.19.2/blob-csi-driver-v1.19.2.tgz
    version: v1.19.2
  - apiVersion: v1
    appVersion: v1.18.0
    created: "2023-05-12T05:37:18.812644959Z"
    description: Azure Blob Storage CSI driver
    digest: 3eac15488da5be7d1e78431929f7cda35bceb1af3fe107ffbd84606e047c9204
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.18.0/blob-csi-driver-v1.18.0.tgz
    version: v1.18.0
  - apiVersion: v1
    appVersion: v1.17.0
    created: "2023-05-12T05:37:18.811405886Z"
    description: Azure Blob Storage CSI driver
    digest: 22cfa17fc5e8d771ff8edd26729266a9a8ee55c0e150df85ef15698f7fe985e9
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.17.0/blob-csi-driver-v1.17.0.tgz
    version: v1.17.0
  - apiVersion: v1
    appVersion: v1.16.0
    created: "2023-05-12T05:37:18.810617872Z"
    description: Azure Blob Storage CSI driver
    digest: bf6249c0e3e3d3d009d4c79ceb7fda9a56c0565b969de753628792ea3ea5ece8
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.16.0/blob-csi-driver-v1.16.0.tgz
    version: v1.16.0
  - apiVersion: v1
    appVersion: v1.15.0
    created: "2023-05-12T05:37:18.809802381Z"
    description: Azure Blob Storage CSI driver
    digest: 8daa35cd4957695cb64b45da05a15b4020df5545a8ac44c4668dad4bba82c8a9
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.15.0/blob-csi-driver-v1.15.0.tgz
    version: v1.15.0
  - apiVersion: v1
    appVersion: v1.14.0
    created: "2023-05-12T05:37:18.809044941Z"
    description: Azure Blob Storage CSI driver
    digest: 442bc579b231aab626b9e474e2c0ed3f101d47d61c99aa9a7f863af7ce268d9d
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.14.0/blob-csi-driver-v1.14.0.tgz
    version: v1.14.0
  - apiVersion: v1
    appVersion: v1.13.0
    created: "2023-05-12T05:37:18.808314776Z"
    description: Azure Blob Storage CSI driver
    digest: b577b0b771138109aa90eb09d56fc07273ca0b584a263ee8f789e35796279f31
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.13.0/blob-csi-driver-v1.13.0.tgz
    version: v1.13.0
  - apiVersion: v1
    appVersion: v1.12.0
    created: "2023-05-12T05:37:18.80753659Z"
    description: Azure Blob Storage CSI driver
    digest: 124e87af2581b374b89a39940698620c23d3eae6dcee518d302461ffea93e9a8
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.12.0/blob-csi-driver-v1.12.0.tgz
    version: v1.12.0
  - apiVersion: v1
    appVersion: v1.11.0
    created: "2023-05-12T05:37:18.806704403Z"
    description: Azure Blob Storage CSI driver
    digest: 07c4d76017491b3d0bdd70de90e814096938bf7916da0c149c3805294bd57560
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.11.0/blob-csi-driver-v1.11.0.tgz
    version: v1.11.0
  - apiVersion: v1
    appVersion: v1.10.0
    created: "2023-05-12T05:37:18.805862161Z"
    description: Azure Blob Storage CSI driver
    digest: 79716efa958385adf57eb3570843e1b4512d8c801e8e070625e94264f3e917a9
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.10.0/blob-csi-driver-v1.10.0.tgz
    version: v1.10.0
  - apiVersion: v1
    appVersion: v1.9.0
    created: "2023-05-12T05:37:18.82494081Z"
    description: Azure Blob Storage CSI driver
    digest: fca0b9215d3277346f68c643fb3ead75158971f0d1945ab01ec559196f3cf842
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.9.0/blob-csi-driver-v1.9.0.tgz
    version: v1.9.0
  - apiVersion: v1
    appVersion: v1.8.0
    created: "2023-05-12T05:37:18.824127616Z"
    description: Azure Blob Storage CSI driver
    digest: 3b78e2ab4f33577c54d4f57276c824717d2ad2aa3741210e938fcaf927bc751f
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.8.0/blob-csi-driver-v1.8.0.tgz
    version: v1.8.0
  - apiVersion: v1
    appVersion: v1.7.0
    created: "2023-05-12T05:37:18.82339047Z"
    description: Azure Blob Storage CSI driver
    digest: 28da5b55c3d2689d6da85eb7da344385e9cb99bdb2af18c24fea93670abfe7ea
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.7.0/blob-csi-driver-v1.7.0.tgz
    version: v1.7.0
  - apiVersion: v1
    appVersion: v1.6.0
    created: "2023-05-12T05:37:18.822630633Z"
    description: Azure Blob Storage CSI driver
    digest: 6f24f2e6623f6f8862e47d4fbdf13b5f351ceec6bb9a4591ef7fc2fca9fc1eef
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.6.0/blob-csi-driver-v1.6.0.tgz
    version: v1.6.0
  - apiVersion: v1
    appVersion: v1.5.0
    created: "2023-05-12T05:37:18.821777624Z"
    description: Azure Blob Storage CSI driver
    digest: 95d14c9b70b319760d388ea47727c8c97e9287867a8852aeb67b7175b52fe8f5
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.5.0/blob-csi-driver-v1.5.0.tgz
    version: v1.5.0
  - apiVersion: v1
    appVersion: v1.4.1
    created: "2023-05-12T05:37:18.820187132Z"
    description: Azure Blob Storage CSI driver
    digest: 5fcf69c449f065fa1d5722e5a7fed8a28000efa790907e9ff4b552c5fbd16d22
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.4.1/blob-csi-driver-v1.4.1.tgz
    version: v1.4.1
  - apiVersion: v1
    appVersion: v1.4.0
    created: "2023-05-12T05:37:18.819503225Z"
    description: Azure Blob Storage CSI driver
    digest: b466543344a6411f6130ba87b093955d39ab8614c6b4ed8505a0a0c96073cb33
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.4.0/blob-csi-driver-v1.4.0.tgz
    version: v1.4.0
  - apiVersion: v1
    appVersion: v1.3.0
    created: "2023-05-12T05:37:18.818801343Z"
    description: Azure Blob Storage CSI driver
    digest: 58d02cb70a3a966b349d62e880b7149fb06ac009474e35e580784fd3c98a5b07
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.3.0/blob-csi-driver-v1.3.0.tgz
    version: v1.3.0
  - apiVersion: v1
    appVersion: v1.2.0
    created: "2023-05-12T05:37:18.815003223Z"
    description: Azure Blob Storage CSI driver
    digest: 27fb89f20b5fddc7329e6d7c2374857b22c1d61592e397a53f47121eea68c344
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.2.0/blob-csi-driver-v1.2.0.tgz
    version: v1.2.0
  - apiVersion: v1
    appVersion: v1.1.0
    created: "2023-05-12T05:37:18.804795701Z"
    description: Azure Blob Storage CSI driver
    digest: a251a55243de207c69ef53f72abee45e93b72fa4fc43dc204b7f1cdfd459acdb
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.1.0/blob-csi-driver-v1.1.0.tgz
    version: v1.1.0
  - apiVersion: v1
    appVersion: v1.0.0
    created: "2023-05-12T05:37:18.804073519Z"
    description: Azure Blob Storage CSI driver
    digest: e83f037a165eafc83a978bd7e6bf6221b052ac34363aecb12e6a73607dc58b89
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.0.0/blob-csi-driver-v1.0.0.tgz
    version: v1.0.0
  - apiVersion: v1
    appVersion: latest
    created: "2023-05-12T05:37:18.802201961Z"
    description: Azure Blob Storage CSI driver
    digest: c1681cd031f5eb9fdb7fd16adf006c77824485f1744dc6b65f2db02c0a1581d6
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/latest/blob-csi-driver-v0.0.0.tgz
    version: v0.0.0
generated: "2023-05-12T05:37:18.801406393Z"
